apiVersion: v1
data:
  CHAIN_PARAMS: |
    {
      "bootstrap_peers": {{ toJson .Values.bootstrap_peers }},
      "default_bootstrap_mutez": "{{ .Values.bootstrap_mutez }}",
      "expected-proof-of-work": {{ toJson .Values.expected_proof_of_work }},

      "full_snapshot_url": {{ toJson .Values.full_snapshot_url }},
      "rolling_snapshot_url": {{ toJson .Values.rolling_snapshot_url }},

      "should_generate_unsafe_deterministic_data": {{ toJson .Values.should_generate_unsafe_deterministic_data }},
      "network": {{ mustToPrettyJson .Values.node_config_network | indent 8 | trim }},
      "proto_command": "{{ .Values.protocol.command }}",
      "protocol_activation": {{ .Values.activation | mustToPrettyJson | indent 8 | trim }}
    }
  NODES: |
{{ .Values.nodes | mustToPrettyJson | indent 4 }}
kind: ConfigMap
metadata:
  name: tezos-config
  namespace: {{ .Release.Namespace }}
---
{{- if (include "tezos.doesZerotierConfigExist" .) }}
apiVersion: v1
data:
  CHAIN_NAME: "{{ .Values.node_config_network.chain_name }}"
  NETWORK_ID: "{{ .Values.zerotier_config.zerotier_network }}"
  ZTAUTHTOKEN: "{{ .Values.zerotier_config.zerotier_token }}"
  NODES: |
{{ .Values.nodes | mustToPrettyJson | indent 4 }}
kind: ConfigMap
metadata:
  name: zerotier-config
  namespace: {{ .Release.Namespace }}
{{- end }}
---
apiVersion: v1
data:
  ACCOUNTS: |
{{ .Values.accounts | toJson | b64enc | indent 4 }}
kind: Secret
metadata:
  name: tezos-secret
  namespace: {{ .Release.Namespace }}
