apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.indexer_statefulset.name }}
  namespace: {{ .Release.Namespace }}
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.indexer_statefulset.name }}
  serviceName: tezos-node
  template:
    metadata:
      labels:
        app: {{ .Values.indexer_statefulset.name }}
        appType: tezos
    spec:
      initContainers:
        - image: registry.gitlab.com/nomadic-labs/tezos-indexer/tezos-indexer:latest
          command: ["/bin/bash","-c"]
          args: [ "/home/tezos/tezos-indexer --db-schema | tee /docker-entrypoint-initdb.d/tezos-indexer-schema.sql" ]
          name: schema-extractor
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: schema-volume
      containers:
        - image: registry.gitlab.com/nomadic-labs/tezos-indexer/tezos-indexer:latest
          name: tezos-indexer
          args:
            - --verbose
            - --debug
            - --verbosity=10
            - --force-from=1
            - --db=postgresql://localhost/tezos
            -  --tezos-url=http://tezos-node-0.tezos-node:8732
            - --edonet
        - image: postgres:alpine
          name: postgres
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: schema-volume
            - mountPath: /var/lib/postgresql/data
              name: indexer-db
          env:
            - name: POSTGRES_USER
              value: tezos
            - name: POSTGRES_DB
              value: tezos
            - name: POSTGRES_PASSWORD
              value: tezosrocks
      volumes:
        - emptyDir: {}
          name: schema-volume
  volumeClaimTemplates:
    - metadata:
        name: indexer-db
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "5Gi"
