apiVersion: v1
kind: Service
metadata:
  name: tezos-node-rpc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8732
  selector:
    app: tezos-baking-node
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: tezos-node
spec:
  clusterIP: None
  selector:
    app: tezos-node
---
apiVersion: v1
kind: Service
metadata:
  name: tezos-baking-node
spec:
  clusterIP: None
  selector:
    app: tezos-baking-node
