apiVersion: v1
kind: Service
metadata:
  name: tezos-bootstrap-node-rpc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8732
  selector:
    app: tezos-bootstrap-node
  type: NodePort
