apiVersion: v1
kind: Service
metadata:
  name: tezos-bootstrap-node-rpc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8732
  selector:
    app: tezos-bootstrap-node
  type: NodePort
---
{{- if not .Values.zerotier_in_use }}
apiVersion: v1
kind: Service
metadata:
  name: tezos-bootstrap-node-p2p
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 9732
  selector:
    app: tezos-bootstrap-node
  type: NodePort
---
{{ end }}
