apiVersion: v1
kind: Service
metadata:
  name: tezos-node-rpc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8732
  selector:
    app: tezos-baking-node
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.regular_node_statefulset.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.regular_node_statefulset.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.baker_statefulset.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.baker_statefulset.name }}
